### ISSUE TITLE
ginkgo ETS cache

### ISSUE THREAD

**Issue by dch** [vaxine-io/vaxine#11]
refactor https://github.com/AntidoteDB/antidote/pull/463

- [x] flatten git commits
- [ ] align with existing code by cleaning up spaces/function names/reformatting & linting
- [ ] add some documentation and background info
- [ ] ensure existing tests pass
- [ ] document remaining issues after this point
